// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityTemplates
{
    static class Vsix
    {
        public const string Id = "ExtensibilityTemplates.0d984c08-344f-469e-84d8-14544574d718";
        public const string Name = "Extensibility Templates";
        public const string Description = @"A collection of project- and item templates for Visual Studio extension authoring.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, templates";
    }
}
